# fly.toml app configuration file generated for poetry-service on 2023-07-05T18:25:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "poetry-service"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
